### ISSUE TITLE
function type will error

### ISSUE THREAD

**Issue by hukangbao** [fabien0102/ts-to-zod#234] opened 2024-04-26 05:28 UTC
## Bug description
if i set es6 function, it will error

### Input
export interface Test {
  getAchievements(input: number): string;
}

```ts
// typescript type or interface causing the output
```

### Expected output
✖ Validating generated types
 ›   Error: 'testFNSchema' is not compatible with 'TestFN':
 ›   Argument of type '{}' is not assignable to parameter of type 'TestFN'.
 ›     Property 'getAchievements' is missing in type '{}' but required in type 
 ›   'TestFN'.
```ts
// Expected Zod schemas
```

### Actual output

```ts
// Actual Zod schemas
```

**Versions**

- Typescript: `v0.0.0`
- Zod: `v0.0.0`

**Comment by tvillaren** [comment] 2024-04-26 07:33
This is a duplicate of https://github.com/fabien0102/ts-to-zod/issues/220

**Closed by tvillaren** 2024-04-26 07:33 UTC
Labels: duplicate
