### ISSUE TITLE
Add appendFileExtension option for referencing back to origional types

### ISSUE THREAD

**Issue by hongkongkiwi** [fabien0102/ts-to-zod#279] opened 2024-10-31 14:25 UTC
I'm using deno and it requires explicit .ts extensions when importing files locally.

So for example this will not work:
`import { type PortKeyConfig } from "./../types/schemas";`

Instead it must be:
`import { type PortKeyConfig } from "./../types/schemas.ts";`

Using node with [ECMAScript](https://nodejs.org/api/esm.html) also requires .js to be added, so I think it's a valuable option either way.

Could you help to add a config value where I can force the file extension to be added? e.g. `appendFileExtension: '.ts'` or something like that?

**Comment by tvillaren** [comment] 2024-10-31 17:45
Hello, 
Thanks for reporting, I believe this is a duplicate of https://github.com/fabien0102/ts-to-zod/issues/259, right?

Feel free to open a PR if you have some time to help the library strive! 🙏

**Comment by hongkongkiwi** [comment] 2024-11-01 04:36
Oh yes it is a duplicate and funnily enough we have the same workaround ;)

**Closed** 2024-11-01 09:19 UTC
