### ISSUE TITLE
"error TS6053, File source.integration.ts not found" and two more files

### ISSUE THREAD

**Issue by TheDesertKing** [fabien0102/ts-to-zod#110] opened 2023-01-22 04:54 UTC
## Bug description

When running:
```npx ts-to-zod userInterface.ts```
Three errors occur, stating that three files are missing: source.integration.ts, source.ts and source.zod.ts.

### Input

```ts
export interface User {
	username: string;
	user_description?: string;
	user_tags?: string[];
	github_account_link?: string;
	following: number[];
	followed_by: number[];
	follower_count: number;
	authored_ideas: number[];
	owned_projects: number[];
	watched_projects: number[];
	date_joined: Date;
	date_updated: Date;
}

export interface NewUser {
	username: string;
	user_description?: string;
	user_tags?: string[];
	github_account_link?: string;

	// These attributes aren't needed / are server
	// Generated

	// following: number[];
	// followed_by: number[];
	// follower_count: number;
	// authored_ideas: number[];
	// owned_projects: number[];
	// watched_projects: number[];
	// date_joined: Date;
	// date_updated: Date;
}
```

### Expected output

```ts
... The generator Zod schema ...
```

### Actual output

⠋ Validating generated typesDeprecationWarning: 'createTypeAliasDeclaration' has been deprecated since v4.8.0. Decorators are no longer supported for this function. Callers should switch to an overload that does not accept a 'decorators' parameter.
⠋ Validating generated types    Error: error TS6053: File 'C:/VS Code/DevIt/devit/front-end/types/source.integration.ts' not found.
      The file is in the program because:
        Root file specified for compilation
      The file is in the program because:
        Root file specified for compilation
    error TS6053: File 'C:/VS Code/DevIt/devit/front-end/types/source.zod.ts' not found.
      The file is in the program because:
        Root file specified for compilation

**Versions**

- Typescript: `v4.9.4`
- Zod: `3.20.2`

**Comment by kjetilhartveit** [comment] 2023-02-27 18:43
Same problem. I don't see any of these files (`source.ts`, `source.integration.ts` etc) in the library files. I had to add the flag `--skipValidation` in order to make it work

**Comment by throw5way** [comment] 2023-08-10 21:12
These files are generated [here](https://github.com/fabien0102/ts-to-zod/blob/8d3b297e4131ef105bfe155b038e4b4f76a7d5fc/src/cli.ts#L274). The problem is Windows-specific, and happens due to incorrect handling of file paths somewhere between TS Compiler API and `ts-to-zod` internals.

I will investigate when I have time, but if your generated schema will be used by `ts-node` or `tsc` later, you can avoid the issue by passing `--skipValidation` flag.

**Comment by schiller-manuel** [comment] 2024-02-06 21:38
closing for now as we now run successfully run the automated tests on windows.

**Closed by schiller-manuel** 2024-02-06 21:38 UTC
