### ISSUE TITLE
Getting `Error: Unknown IndexedAccessTypeNode.objectType type` when trying to use unions

### ISSUE THREAD

**Issue by la55u** [fabien0102/ts-to-zod#147] opened 2023-07-19 15:16 UTC
## Bug description

Running into an error when trying to use the library. Am I doing it wrong or is this not supported? VSCode seems to recognize the unions just fine (see the screenshot). The problem is I cannot change the input file because it's generated by another tool.
Thank you for your help!

```
> pnpm ts-to-zod

StatusUnion
RequestBody
    Error: Unknown IndexedAccessTypeNode.objectType type

```
![image](https://github.com/fabien0102/ts-to-zod/assets/30611343/cc6bbe6e-bc87-47ea-b5e7-53ae7087e4ef)

### Input

```ts
export const Status = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
} as const;

export type StatusUnion = (typeof Status)[keyof typeof Status];

export interface RequestBody {
  status: StatusUnion;
}

```

### Expected output

```ts
export const statusUnionSchema = z.union([z.literal("ACTIVE"), z.literal("INACTIVE")]);

export const requestBodySchema = z.object({
  status: statusUnionSchema,
});
```
(Or anything else that doesn't give an error during generation.)

### Actual output

```
Error: Unknown IndexedAccessTypeNode.objectType type
```

**Versions**

- Typescript: `v4.9.4`
- Zod: `v3.21.4`

**Comment by sannicm** [comment] 2023-11-14 10:23
Is there any plans on implementing these? It would really be useful to have zod generation from these kind of union types.

**Comment by matboros** [comment] 2023-11-14 10:33
We also ran into this issue, and at the moment it is preventing the automation around zod.

**Comment by fabien0102** [comment] 2023-11-14 13:44
Thanks for bringing my attention to this issue, I never used this syntax before, supporting it doesn't really seem very straight forward and I don't have any time to dedicate to this project lately. This said, if somebody want to give a try, I will be happy to review.

**Comment by tvillaren** [comment] 2024-03-06 22:18
This is a duplicate of #116

**Closed by tvillaren** 2024-03-06 22:18 UTC
Labels: duplicate
